engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  
exclude_paths:
- "**/webapp/assets/css/"
- "**/webapp/plugins/"
